_max_hart_id = 0;

MEMORY
{
    ROM   (rxai!w) : ORIGIN = 0x90000000, LENGTH = 128K
    FLASH (rxai!w) : ORIGIN = 0xA0000000, LENGTH = 4M
    RAM_OC   (wxa) : ORIGIN = 0x62FC0000, LENGTH = 320K
    RAM_WIFI (wxa) : ORIGIN = 0x63010000, LENGTH = 160K
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM_OC);
REGION_ALIAS("REGION_BSS", RAM_OC);
REGION_ALIAS("REGION_HEAP", RAM_OC);
REGION_ALIAS("REGION_STACK", RAM_OC);
