_max_hart_id = 0;

MEMORY
{
    ROM   (rx)  : ORIGIN = 0x90000000, LENGTH = 128K
    FLASH (wxa) : ORIGIN = 0xA0000000, LENGTH = 8M
    OCRAM (wxa) : ORIGIN = 0x22FC0000, LENGTH = 320K
    WRAM  (wxa) : ORIGIN = 0x23010000, LENGTH = 160K
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", OCRAM);
REGION_ALIAS("REGION_BSS", OCRAM);
REGION_ALIAS("REGION_HEAP", OCRAM);
REGION_ALIAS("REGION_STACK", OCRAM);
